sudo: false
language: android
jdk:
    - oraclejdk8
env:
    global:
        - GRADLE_OPTS='-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
        - TERM=dumb
cache:
    directories:
        - $HOME/.gradle
before_install:
    - echo yes | android update sdk --no-ui --all --filter tools
    - echo yes | android update sdk --no-ui --all --filter platform-tools
    - echo yes | android update sdk --no-ui --all --filter extra-android-m2repository
    - mkdir -p "$ANDROID_HOME"/licenses
    - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME"/licenses/android-sdk-license
script:
    - ./gradlew check
